export interface ITypes {
  TOGGLE_OVERLAY: string;
  TOGGLE_WORKS_CONTENT: string;
  TOGGLE_WORKS_CONTENT_ANIMATION: string;
  UPDATE_CIRCLE: string;
}

const types: ITypes = {
  TOGGLE_OVERLAY: 'TOGGLE_OVERLAY',
  TOGGLE_WORKS_CONTENT: 'TOGGLE_WORKS_CONTENT',
  TOGGLE_WORKS_CONTENT_ANIMATION: 'TOGGLE_WORKS_CONTENT_ANIMATION',
  UPDATE_CIRCLE: 'UPDATE_CIRCLE',
};

export default types;
